#line 2 "psl_input.c"

#line 4 "psl_input.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer psl_yy_create_buffer
#define yy_delete_buffer psl_yy_delete_buffer
#define yy_flex_debug psl_yy_flex_debug
#define yy_init_buffer psl_yy_init_buffer
#define yy_flush_buffer psl_yy_flush_buffer
#define yy_load_buffer_state psl_yy_load_buffer_state
#define yy_switch_to_buffer psl_yy_switch_to_buffer
#define yyin psl_yyin
#define yyleng psl_yyleng
#define yylex psl_yylex
#define yylineno psl_yylineno
#define yyout psl_yyout
#define yyrestart psl_yyrestart
#define yytext psl_yytext
#define yywrap psl_yywrap
#define yyalloc psl_yyalloc
#define yyrealloc psl_yyrealloc
#define yyfree psl_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE psl_yyrestart(psl_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t psl_yyleng;

extern FILE *psl_yyin, *psl_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE psl_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-psl_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < psl_yyleng; ++yyl )\
                    if ( psl_yytext[yyl] == '\n' )\
                        --psl_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up psl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up psl_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via psl_yyrestart()), so that the user can continue scanning by
	 * just pointing psl_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when psl_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t psl_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow psl_yywrap()'s to do buffer switches
 * instead of setting up a fresh psl_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void psl_yyrestart (FILE *input_file  );
void psl_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE psl_yy_create_buffer (FILE *file,int size  );
void psl_yy_delete_buffer (YY_BUFFER_STATE b  );
void psl_yy_flush_buffer (YY_BUFFER_STATE b  );
void psl_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void psl_yypop_buffer_state (void );

static void psl_yyensure_buffer_stack (void );
static void psl_yy_load_buffer_state (void );
static void psl_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER psl_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE psl_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE psl_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE psl_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *psl_yyalloc (yy_size_t  );
void *psl_yyrealloc (void *,yy_size_t  );
void psl_yyfree (void *  );

#define yy_new_buffer psl_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        psl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        psl_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define psl_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *psl_yyin = (FILE *) 0, *psl_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int psl_yylineno;

int psl_yylineno = 1;

extern char *psl_yytext;
#define yytext_ptr psl_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up psl_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	psl_yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 137
#define YY_END_OF_BUFFER 138
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[321] =
    {   0,
        1,    1,  138,  136,    1,    1,   41,  136,   16,  121,
      122,   55,   56,  126,   18,  134,   57,  131,  131,  128,
      129,   23,   38,   27,  127,   82,  133,   78,   72,   71,
      133,  133,  133,  133,   73,   74,   70,   63,  125,   33,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  123,   14,  124,
       31,    1,   40,    0,  135,   15,   54,    2,   17,    0,
      131,    0,    0,   52,    6,    0,   21,   22,   37,   26,
       25,  133,   81,   79,   80,   77,   75,   76,  133,    5,
      133,  133,  133,   69,   59,    0,    0,   60,   32,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,   64,
      133,  133,   66,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,    0,    0,   13,
       30,   29,   28,   39,  130,    0,    0,   19,   20,   36,
       24,  133,  133,  133,  133,   62,   61,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,   58,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,  133,  133,  133,   34,   11,
       12,  132,  133,    7,  133,    3,  133,  133,  133,   42,
      119,  120,  133,  133,  133,  133,  133,  133,  109,  133,

      133,  133,  133,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  133,   35,  132,    4,  133,  118,
      133,  133,  133,  133,  133,  133,  133,  133,  133,   88,
      108,  133,  133,  133,  133,  133,  133,  133,  133,  133,
       45,   65,  133,  117,  133,  133,  133,   48,  133,   87,
      113,  133,  133,   51,    8,    9,  133,  133,  105,  107,
      133,  133,   43,   53,  133,   49,   44,  133,  133,  115,
      116,  133,  133,   93,   86,  111,  112,   10,  133,  133,
       68,  104,  106,  133,   67,  133,  133,   47,  133,  114,
       46,  133,   91,   92,  110,  133,  133,  133,   83,   84,

       50,   97,   90,  133,  133,  133,   95,   96,  133,   85,
      103,   94,   89,  102,  133,   99,  101,   98,  100,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    6,    1,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   26,   27,   26,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   31,   37,
       33,   38,   39,   40,   41,   33,   42,   43,   33,   33,
       44,    1,   45,   46,   47,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   33,   33,   57,   58,   59,
       60,   61,   62,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    2,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    3,    3,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    4,    3,    3,    3,
        3,    3,    3,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[325] =
    {   0,
        0,    0,  379,  380,   74,   76,  356,  372,  369,  380,
      380,  365,  380,  380,   67,  380,  380,   77,   67,   67,
      380,   75,  352,   76,  380,   71,    0,   75,  348,    0,
      336,  346,  331,  331,    0,    0,  364,   99,  380,  292,
       58,   59,  318,   53,  305,  301,  304,  302,  309,  297,
       53,  307,   71,  298,   65,   74,   76,  380,  118,  380,
       99,  144,  335,  351,  380,  380,  380,  380,  380,  132,
      137,  140,  133,  380,  380,  332,  333,  380,  331,  380,
      329,    0,    0,    0,    0,    0,    0,    0,  317,    0,
      315,  315,  307,  380,  380,  302,  323,  380,  380,  285,

      276,  290,  282,  277,  292,  287,  273,  274,  272,    0,
      284,   98,    0,  270,  273,  268,   25,   71,  281,  274,
      104,  279,  272,  262,  263,  265,  261,  300,  299,  380,
      380,  380,  380,  380,  145,  157,    0,  380,  380,  380,
      380,  282,  292,  280,  290,  380,  380,  254,  268,  255,
      257,  261,  262,  252,  258,  261,  256,    0,  255,  254,
      240,  252,  242,  246,  249,  234,  240,  246,  237,  237,
      235,  238,  237,  232,  234,  235,  238,  225,    0,  380,
      380,    0,  259,    0,  249,    0,  220,  214,  220,  230,
        0,    0,  216,  221,  119,  217,  227,  214,  134,  225,

      223,  203,  223,  220,  219,  210,  210,  203,  208,  212,
      208,  205,  211,  206,  244,    0,    0,    0,  232,    0,
      195,  206,  209,  190,  204,  197,  183,  186,  197,    0,
      380,  118,  196,  186,  196,  182,  187,  194,  191,  179,
        0,    0,  183,  167,  177,  181,  180,    0,  211,    0,
      173,  178,  188,    0,    0,    0,  173,  172,  217,  140,
      167,  153,    0,    0,  167,    0,    0,  151,  163,  166,
        0,  147,  151,  175,    0,  163,    0,    0,  152,  149,
        0,  380,  380,  154,    0,  135,  151,    0,  151,  380,
        0,  136,  153,    0,  380,  142,  148,  138,    0,    0,

        0,  176,  380,  126,  143,  129,  145,    0,  186,    0,
      179,  380,  380,  380,  137,  182,   98,  380,  380,  380,
      226,  229,   89,  231
    } ;

static yyconst flex_int16_t yy_def[325] =
    {   0,
      320,    1,  320,  320,  320,  320,  320,  321,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  320,  320,  320,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  320,  320,  320,
      320,  320,  320,  321,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  320,  320,  320,  320,  320,  320,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  323,  320,  320,  320,
      320,  322,  322,  322,  322,  320,  320,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  320,
      320,  324,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,

      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  324,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      320,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  322,
      322,  322,  322,  322,  322,  322,  322,  322,  322,  320,
      322,  322,  322,  322,  322,  320,  322,  322,  322,  322,
      322,  320,  320,  322,  322,  322,  322,  322,  322,  320,
      322,  322,  320,  322,  320,  322,  322,  322,  322,  322,

      322,  322,  320,  322,  322,  322,  320,  322,  322,  322,
      322,  320,  320,  320,  322,  322,  322,  320,  320,    0,
      320,  320,  320,  320
    } ;

static yyconst flex_int16_t yy_nxt[456] =
    {   0,
        4,    5,    6,    7,    8,    4,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   27,   28,   29,   30,
       27,   31,   27,   27,   27,   32,   33,   27,   27,   34,
       35,   36,   37,   38,   39,   40,   27,   41,   42,   43,
       27,   44,   45,   46,   27,   47,   27,   48,   49,   50,
       51,   27,   52,   53,   54,   55,   27,   56,   57,   27,
       27,   58,   59,   60,   61,   62,   62,   62,   62,   68,
       70,  165,   71,   71,   71,   74,  166,   76,   75,   69,
       70,  182,   71,   71,   71,   77,   78,   80,   81,   83,

       84,  319,   72,   86,   87,  131,  100,   72,   95,   96,
      102,   97,  114,   85,  101,  115,  105,   88,  103,  106,
       98,  107,  117,  121,  167,   72,  118,   72,  123,  124,
      128,   72,  122,  125,  126,  127,   72,  231,  119,  129,
       73,  168,   73,  283,  132,   62,   62,  135,  135,  135,
       70,  159,   71,   71,   71,  136,  136,  136,   72,  171,
      135,  135,  135,   72,  160,  259,  161,  172,  173,  260,
      270,  133,  136,  136,  136,  226,  276,  227,  293,  307,
      232,   72,  314,   72,  316,  318,  137,   72,  317,  313,
      130,  312,   72,  311,  310,  309,  306,  305,  304,  303,

      302,  301,  300,  137,  299,  298,  284,  297,  296,  295,
      292,  291,  290,  271,  289,  288,  287,  286,  285,  277,
      282,  294,  308,  281,  280,  315,   64,   64,   64,   64,
       82,   82,   82,  217,  217,  279,  278,  275,  274,  273,
      272,  269,  268,  267,  266,  265,  264,  263,  262,  261,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  230,  229,  228,  225,
      224,  223,  222,  221,  220,  219,  218,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,

      203,  202,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  181,  180,  179,  178,  177,  176,  175,  174,  170,
      169,  164,  163,  162,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,   65,  134,  120,  116,  113,
      112,  111,  110,  109,  108,  104,   99,   94,   93,   92,
       91,   90,   89,   79,   67,   66,   65,   63,  320,    3,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320
    } ;

static yyconst flex_int16_t yy_chk[456] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    5,    5,    6,    6,   15,
       19,  117,   19,   19,   19,   20,  117,   22,   20,   15,
       18,  323,   18,   18,   18,   22,   22,   24,   24,   26,

       26,  317,   18,   28,   28,   61,   41,   18,   38,   38,
       42,   38,   51,   26,   41,   51,   44,   28,   42,   44,
       38,   44,   53,   55,  118,   18,   53,   18,   56,   56,
       59,   18,   55,   56,   57,   57,   18,  199,   53,   59,
       18,  118,   18,  260,   61,   62,   62,   70,   70,   70,
       71,  112,   71,   71,   71,   72,   72,   72,   73,  121,
      135,  135,  135,   73,  112,  232,  112,  121,  121,  232,
      244,   61,  136,  136,  136,  195,  251,  195,  274,  302,
      199,   73,  311,   73,  315,  316,   72,   73,  315,  309,
       59,  307,   73,  306,  305,  304,  298,  297,  296,  293,

      292,  289,  287,  136,  286,  284,  260,  280,  279,  276,
      273,  272,  270,  244,  269,  268,  265,  262,  261,  251,
      259,  274,  302,  258,  257,  311,  321,  321,  321,  321,
      322,  322,  322,  324,  324,  253,  252,  249,  247,  246,
      245,  243,  240,  239,  238,  237,  236,  235,  234,  233,
      229,  228,  227,  226,  225,  224,  223,  222,  221,  219,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  198,  197,  196,  194,
      193,  190,  189,  188,  187,  185,  183,  178,  177,  176,
      175,  174,  173,  172,  171,  170,  169,  168,  167,  166,

      165,  164,  163,  162,  161,  160,  159,  157,  156,  155,
      154,  153,  152,  151,  150,  149,  148,  145,  144,  143,
      142,  129,  128,  127,  126,  125,  124,  123,  122,  120,
      119,  116,  115,  114,  111,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   97,   96,   93,   92,   91,
       89,   81,   79,   77,   76,   64,   63,   54,   52,   50,
       49,   48,   47,   46,   45,   43,   40,   37,   34,   33,
       32,   31,   29,   23,   12,    9,    8,    7,    3,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[138] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int psl_yy_flex_debug;
int psl_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *psl_yytext;
#line 1 "psl_input.l"
/***************************************************************  -*-C-*-  ***/
#line 4 "psl_input.l"
/**CFile***********************************************************************

  FileName    [psl_input.l]

  PackageName [parser.psl]

  Synopsis    [Lexical analyzer for the PSL specification input language]

  SeeAlso     [psl_grammar.y]

  Author      [Roberto Cavada]

  Copyright   [
  This file is part of the ``parser.psl'' package of NuSMV version 2.
  Copyright (C) 2005 by FBK-irst.

  NuSMV version 2 is free software; you can redistribute it and/or
  modify it under the terms of the GNU Lesser General Public
  License as published by the Free Software Foundation; either
  version 2 of the License, or (at your option) any later version.

  NuSMV version 2 is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public
  License along with this library; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307  USA.

  For more information on NuSMV see <http://nusmv.fbk.eu>
  or email to <nusmv-users@fbk.eu>.
  Please report bugs to <nusmv-users@fbk.eu>.

  To contact the NuSMV development board, email to <nusmv@fbk.eu>. ]

******************************************************************************/

#if HAVE_CONFIG_H
# include "nusmv-config.h"
#endif

#include <stdio.h>
#include <limits.h>
#include <stdlib.h>
#include "utils/portability.h" /* for errno */

/* The below code is only meaningful for flex version 2.5.31 which is
   buggy since it does not define the yy_prev_more_offset static
   variable */
#if defined YY_FLEX_SUBMINOR_VERSION &&         \
  defined YY_FLEX_MAJOR_VERSION &&              \
  defined YY_FLEX_MINOR_VERSION
#if YY_FLEX_SUBMINOR_VERSION == 31 &&           \
  YY_FLEX_MINOR_VERSION == 5 &&                 \
  YY_FLEX_MAJOR_VERSION == 2
static int yy_prev_more_offset = 0;
#endif
#endif

#if NUSMV_HAVE_STRING_H
#include <string.h> /* for strdup */
#else
char* strdup(const char*); /* forward declaration */
#endif


#include "pslExpr.h"
#include "psl_grammar.h"

static char rcsid[] UTIL_UNUSED = "$Id: psl_input.l,v 1.1.2.21.6.8 2009-11-02 17:50:12 nusmv Exp $";

static int psl_skip_comment ARGS((void));
EXTERN void psl_yyerror ARGS((char* s, ...));


#if NUSMV_HAVE_ERRNO_H
#define YY_INPUT(buf, result, max_size) \
        if ( YY_CURRENT_BUFFER->yy_is_interactive ) \
                { \
                int c = '*', n; \
                for (n=0; n<max_size && \
                     (c = getc(psl_yyin)) != EOF && \
                     c!=' ' && c!='\n' && c!='\t' && c!='\r' && c!='\f'; ++n ) \
                        buf[n] = (char) c; \
                if (c==' ' || c=='\n' || c=='\t' || c=='\r' || c=='\f') buf[n++] = (char) c; \
                if (c == EOF && ferror(psl_yyin)) YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
        errno=0; \
                while ( (result = fread(buf, 1, max_size, psl_yyin))==0 && ferror(psl_yyin)) \
                        { \
                        if(errno != EINTR) \
                                { \
                                YY_FATAL_ERROR( "input in flex scanner failed" ); \
                                break; \
                                } \
                        errno=0; \
                        clearerr(psl_yyin); \
                        } \
                }
#else /* NUSMV_HAVE_ERRNO_H */
#define YY_INPUT(buf, result, max_size) \
        if ( YY_CURRENT_BUFFER->yy_is_interactive ) \
                { \
                int c = '*', n; \
                for (n=0; n<max_size && \
                     (c = getc(psl_yyin)) != EOF && \
                     c!=' ' && c!='\n' && c!='\t' && c!='\r' && c!='\f'; ++n ) \
                        buf[n] = (char) c; \
                if (c==' ' || c=='\n' || c=='\t' || c=='\r' || c=='\f') buf[n++] = (char) c; \
                if (c == EOF && ferror(psl_yyin)) YY_FATAL_ERROR( "input in flex scanner failed" ); \
                result = n; \
                } \
        else \
                { \
                while ( (result = fread(buf, 1, max_size, psl_yyin))==0 && ferror(psl_yyin)) \
                        { \
                        clearerr(psl_yyin); \
                        } \
                }
#endif /* NUSMV_HAVE_ERRNO_H */


/* Word operation tokens */
/* READ & WRITE? */
#line 836 "psl_input.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int psl_yylex_destroy (void );

int psl_yyget_debug (void );

void psl_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE psl_yyget_extra (void );

void psl_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *psl_yyget_in (void );

void psl_yyset_in  (FILE * in_str  );

FILE *psl_yyget_out (void );

void psl_yyset_out  (FILE * out_str  );

yy_size_t psl_yyget_leng (void );

char *psl_yyget_text (void );

int psl_yyget_lineno (void );

void psl_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int psl_yywrap (void );
#else
extern int psl_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( psl_yytext, psl_yyleng, 1, psl_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( psl_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( psl_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, psl_yyin))==0 && ferror(psl_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(psl_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int psl_yylex (void);

#define YY_DECL int psl_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after psl_yytext and psl_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 301 "psl_input.l"


#line 1021 "psl_input.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! psl_yyin )
			psl_yyin = stdin;

		if ( ! psl_yyout )
			psl_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			psl_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE );
		}

		psl_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of psl_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 321 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 380 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < psl_yyleng; ++yyl )
				if ( psl_yytext[yyl] == '\n' )
					   
    psl_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 303 "psl_input.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 304 "psl_input.l"
{ psl_skip_comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 305 "psl_input.l"
{ return TKTRUE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 306 "psl_input.l"
{ return TKFALSE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 308 "psl_input.l"
{ return TKINCONTEXT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 309 "psl_input.l"
{ return TKEQDEF; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 310 "psl_input.l"
{ return TKNAME; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 312 "psl_input.l"
{ psl_yylval.operator = TKFORALL; return TKFORALL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 313 "psl_input.l"
{ psl_yylval.operator = TKFORANY; return TKFORANY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 314 "psl_input.l"
{ return TKBOOLEAN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 316 "psl_input.l"
{ psl_yylval.operator = TKPIPEMINUSGT; return TKPIPEMINUSGT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 317 "psl_input.l"
{ psl_yylval.operator = TKPIPEEQGT; return TKPIPEEQGT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 318 "psl_input.l"
{ psl_yylval.operator = TKPIPEPIPE; return TKPIPEPIPE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 319 "psl_input.l"
{ psl_yylval.operator = TKPIPE; return TKPIPE; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 321 "psl_input.l"
{ psl_yylval.operator = TKAMPERSANDAMPERSAND; return TKAMPERSANDAMPERSAND; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 322 "psl_input.l"
{ psl_yylval.operator = TKAMPERSAND; return TKAMPERSAND; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 324 "psl_input.l"
{ psl_yylval.operator = TKMINUSGT; return TKMINUSGT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 325 "psl_input.l"
{ psl_yylval.operator = TKMINUS; return TKMINUS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 327 "psl_input.l"
{ psl_yylval.operator = TKLTMINUSGT; return TKLTMINUSGT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 328 "psl_input.l"
{ psl_yylval.operator = TKLTLTLT; return TKLTLTLT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 329 "psl_input.l"
{ psl_yylval.operator = TKLTLT; return TKLTLT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 330 "psl_input.l"
{ psl_yylval.operator = TKLE; return TKLE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 331 "psl_input.l"
{ psl_yylval.operator = TKLT; return TKLT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 333 "psl_input.l"
{ psl_yylval.operator = TKGTGTGT; return TKGTGTGT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 334 "psl_input.l"
{ psl_yylval.operator = TKGTGT; return TKGTGT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 335 "psl_input.l"
{ psl_yylval.operator = TKGE; return TKGE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 336 "psl_input.l"
{ psl_yylval.operator = TKGT; return TKGT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 338 "psl_input.l"
{ psl_yylval.operator = TKTILDEPIPE; return TKTILDEPIPE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 339 "psl_input.l"
{ psl_yylval.operator = TKTILDECARET; return TKTILDECARET; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 340 "psl_input.l"
{ psl_yylval.operator = TKTILDEAMPERSAND; return TKTILDEAMPERSAND; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 341 "psl_input.l"
{ psl_yylval.operator = TKTILDE; return TKTILDE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 343 "psl_input.l"
{ psl_yylval.operator = TKCARETTILDE; return TKCARETTILDE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 344 "psl_input.l"
{ psl_yylval.operator = TKCARET; return TKCARET; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 345 "psl_input.l"
{ psl_yylval.operator = TKXOR; return TKXOR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 346 "psl_input.l"
{ psl_yylval.operator = TKXNOR; return TKXNOR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 348 "psl_input.l"
{ psl_yylval.operator = TKEQEQEQ; return TKEQEQEQ; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 349 "psl_input.l"
{ psl_yylval.operator = TKEQEQ; return TKEQEQ; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 350 "psl_input.l"
{ psl_yylval.operator = TKEQ; return TKEQ; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 352 "psl_input.l"
{ psl_yylval.operator = TKBANGEQEQ; return TKBANGEQEQ; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 353 "psl_input.l"
{ psl_yylval.operator = TKBANGEQ; return TKBANGEQ; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 354 "psl_input.l"
{ psl_yylval.operator = TKBANG; return TKBANG; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 356 "psl_input.l"
{ psl_yylval.operator = TKBOOL; return TKBOOL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 357 "psl_input.l"
{ psl_yylval.operator = TKWRESIZE; return TKWRESIZE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 358 "psl_input.l"
{ psl_yylval.operator = TKWSIZEOF; return TKWSIZEOF; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 359 "psl_input.l"
{ psl_yylval.operator = TKWTOINT; return TKWTOINT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 360 "psl_input.l"
{ psl_yylval.operator = TKUWCONST; return TKUWCONST; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 361 "psl_input.l"
{ psl_yylval.operator = TKSWCONST; return TKSWCONST; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 362 "psl_input.l"
{ psl_yylval.operator = TKWORD1; return TKWORD1; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 363 "psl_input.l"
{ psl_yylval.operator = TKSIGNED; return TKSIGNED; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 364 "psl_input.l"
{ psl_yylval.operator = TKUNSIGNED; return TKUNSIGNED; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 365 "psl_input.l"
{ psl_yylval.operator = TKEXTEND; return TKEXTEND; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 366 "psl_input.l"
{ psl_yylval.operator = TKWCONCATENATION; return TKWCONCATENATION; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 367 "psl_input.l"
{ psl_yylval.operator = TKWSELECT; return TKWSELECT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 369 "psl_input.l"
{ psl_yylval.operator = TKSPLATSPLAT; return TKSPLATSPLAT; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 370 "psl_input.l"
{ psl_yylval.operator = TKSPLAT; return TKSPLAT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 372 "psl_input.l"
{ psl_yylval.operator = TKPLUS; return TKPLUS; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 373 "psl_input.l"
{ psl_yylval.operator = TKSLASH; return TKSLASH; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 374 "psl_input.l"
{ psl_yylval.operator = TKPERCENT; return TKPERCENT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 376 "psl_input.l"
{ psl_yylval.operator = TKLBSPLAT; return TKLBSPLAT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 377 "psl_input.l"
{ psl_yylval.operator = TKLBEQ; return TKLBEQ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 378 "psl_input.l"
{ psl_yylval.operator = TKLBMINUSGT; return TKLBMINUSGT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 379 "psl_input.l"
{ psl_yylval.operator = TKLBPLUSRB; return TKLBPLUSRB; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 380 "psl_input.l"
{ return TKLB; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 382 "psl_input.l"
{ psl_yylval.operator = TKIN; return TKIN; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 383 "psl_input.l"
{ psl_yylval.operator = TKUNION; return TKUNION; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 384 "psl_input.l"
{ return TKOR; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 385 "psl_input.l"
{ return TKPOSEDGE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 386 "psl_input.l"
{ return TKNEGEDGE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 388 "psl_input.l"
{ psl_yylval.operator = TKXBANG; return TKXBANG; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 389 "psl_input.l"
{ psl_yylval.operator = TKX; return TKX; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 391 "psl_input.l"
{ psl_yylval.operator = TKG; return TKG; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 392 "psl_input.l"
{ psl_yylval.operator = TKF; return TKF; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 393 "psl_input.l"
{ psl_yylval.operator = TKU; return TKU; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 394 "psl_input.l"
{ psl_yylval.operator = TKW; return TKW; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 396 "psl_input.l"
{ psl_yylval.operator = TKEG; return TKEG; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 397 "psl_input.l"
{ psl_yylval.operator = TKEX; return TKEX; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 398 "psl_input.l"
{ psl_yylval.operator = TKEF; return TKEF; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 399 "psl_input.l"
{ psl_yylval.operator = TKE; return TKE; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 401 "psl_input.l"
{ psl_yylval.operator = TKAG; return TKAG; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 402 "psl_input.l"
{ psl_yylval.operator = TKAX; return TKAX; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 403 "psl_input.l"
{ psl_yylval.operator = TKAF; return TKAF; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 404 "psl_input.l"
{ psl_yylval.operator = TKA; return TKA; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 406 "psl_input.l"
{ return TKPROPERTY; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 407 "psl_input.l"
{ return TKSEQUENCE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 408 "psl_input.l"
{ return TKSEREFORGR; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 409 "psl_input.l"
{ return TKPSLSPEC; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 412 "psl_input.l"
{ psl_yylval.operator = TKALWAYS; return TKALWAYS; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 413 "psl_input.l"
{ psl_yylval.operator = TKNEVER; return TKNEVER; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 414 "psl_input.l"
{ psl_yylval.operator = TKEVENTUALLYBANG; return TKEVENTUALLYBANG; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 417 "psl_input.l"
{ psl_yylval.operator = TKWITHINBANG_; return TKWITHINBANG_; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 418 "psl_input.l"
{ psl_yylval.operator = TKWITHINBANG; return TKWITHINBANG; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 419 "psl_input.l"
{ psl_yylval.operator = TKWITHIN_; return TKWITHIN_; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 420 "psl_input.l"
{ psl_yylval.operator = TKWITHIN; return TKWITHIN; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 422 "psl_input.l"
{ psl_yylval.operator = TKWHILENOTBANG_; return TKWHILENOTBANG_; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 423 "psl_input.l"
{ psl_yylval.operator = TKWHILENOTBANG; return TKWHILENOTBANG; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 424 "psl_input.l"
{ psl_yylval.operator = TKWHILENOT_; return TKWHILENOT_; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 425 "psl_input.l"
{ psl_yylval.operator = TKWHILENOT; return TKWHILENOT; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 427 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_ABANG; return TKNEXT_EVENT_ABANG; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 428 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_A; return TKNEXT_EVENT_A; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 429 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_EBANG; return TKNEXT_EVENT_EBANG; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 430 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT_E; return TKNEXT_EVENT_E; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 431 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENTBANG; return TKNEXT_EVENTBANG; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 432 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EVENT; return TKNEXT_EVENT; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 433 "psl_input.l"
{ psl_yylval.operator = TKNEXT_ABANG; return TKNEXT_ABANG; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 434 "psl_input.l"
{ psl_yylval.operator = TKNEXT_A; return TKNEXT_A; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 435 "psl_input.l"
{ psl_yylval.operator = TKNEXT_EBANG; return TKNEXT_EBANG; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 436 "psl_input.l"
{ psl_yylval.operator = TKNEXT_E; return TKNEXT_E; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 437 "psl_input.l"
{ psl_yylval.operator = TKNEXTBANG; return TKNEXTBANG; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 438 "psl_input.l"
{ psl_yylval.operator = TKNEXT; return TKNEXT; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 440 "psl_input.l"
{ psl_yylval.operator = TKBEFOREBANG_; return TKBEFOREBANG_; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 441 "psl_input.l"
{ psl_yylval.operator = TKBEFOREBANG; return TKBEFOREBANG; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 442 "psl_input.l"
{ psl_yylval.operator = TKBEFORE_; return TKBEFORE_; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 443 "psl_input.l"
{ psl_yylval.operator = TKBEFORE; return TKBEFORE; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 445 "psl_input.l"
{ psl_yylval.operator = TKUNTILBANG_; return TKUNTILBANG_; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 446 "psl_input.l"
{ psl_yylval.operator = TKUNTILBANG; return TKUNTILBANG; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 447 "psl_input.l"
{ psl_yylval.operator = TKUNTIL_; return TKUNTIL_; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 448 "psl_input.l"
{ psl_yylval.operator = TKUNTIL; return TKUNTIL; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 450 "psl_input.l"
{ return TKABORT; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 452 "psl_input.l"
{ return TKCASE; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 453 "psl_input.l"
{ return TKENDCASE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 455 "psl_input.l"
{ return TKLP; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 456 "psl_input.l"
{ return TKRP; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 457 "psl_input.l"
{ return TKLC; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 458 "psl_input.l"
{ return TKRC; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 459 "psl_input.l"
{ return TKRB; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 460 "psl_input.l"
{ return TKCOMMA; }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 461 "psl_input.l"
{ return TKQUESTIONMARK; }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 462 "psl_input.l"
{ return TKCOLON; }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 463 "psl_input.l"
{ return TKSEMI; }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 466 "psl_input.l"
{
                                          psl_yylval.fval = strdup(psl_yytext);
                                          return (TKREALNUMBER);
                                        }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 470 "psl_input.l"
{
                      long tmp;
                      char* endptr;

                      errno = 0;
                      tmp = strtol(psl_yytext, &endptr, 10);

                      /* range errors */
                      if ((errno == ERANGE && \
                           (tmp == LONG_MAX || tmp == LONG_MIN))
                          || (errno != 0 && tmp == 0)

                          /* no digits found */
                          || (endptr == psl_yytext)

                          /* garbage after digits */
                          || (*endptr != '\0')

                          /* as an additional check, verify that the value can
                             fit into an ordinary int. tmp can not be negative */
                          || (tmp < 0) || (INT_MAX < tmp)) {

                        rpterr("illegal integer: \"%s\"", psl_yytext);
                      }

                      /* here tmp can be safely cast to int */
                      psl_yylval.ival  = (int)(tmp);

                      return TKNUMBER;
                     }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 501 "psl_input.l"
{
                 psl_yylval.wval = strdup(psl_yytext);
                 return(TKWORDNUMBER);
               }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 507 "psl_input.l"
{ psl_yylval.idname=strdup(psl_yytext); return TKATOM; }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 509 "psl_input.l"
{ return TKDOT; }
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 511 "psl_input.l"
{ psl_yylval.idname=strdup(psl_yytext); return TKATOM; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 514 "psl_input.l"
{ return TKEOF; }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 516 "psl_input.l"
{ psl_yyerror("Invalid character: %s", psl_yytext); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 518 "psl_input.l"
ECHO;
	YY_BREAK
#line 1840 "psl_input.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed psl_yyin at a new source and called
			 * psl_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = psl_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( psl_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * psl_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of psl_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					psl_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			psl_yyrestart(psl_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) psl_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 321 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 321 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 320);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up psl_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --psl_yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					psl_yyrestart(psl_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( psl_yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve psl_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    psl_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void psl_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        psl_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            psl_yy_create_buffer(psl_yyin,YY_BUF_SIZE );
	}

	psl_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	psl_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void psl_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		psl_yypop_buffer_state();
	 *		psl_yypush_buffer_state(new_buffer);
     */
	psl_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	psl_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (psl_yywrap()) processing, but the only time this flag
	 * is looked at is after psl_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void psl_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	psl_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE psl_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) psl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) psl_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	psl_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with psl_yy_create_buffer()
 * 
 */
    void psl_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		psl_yyfree((void *) b->yy_ch_buf  );

	psl_yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a psl_yyrestart() or at EOF.
 */
    static void psl_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	psl_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then psl_yy_init_buffer was _probably_
     * called from psl_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 1;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void psl_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		psl_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void psl_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	psl_yyensure_buffer_stack();

	/* This block is copied from psl_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from psl_yy_switch_to_buffer. */
	psl_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void psl_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	psl_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		psl_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void psl_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)psl_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in psl_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)psl_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in psl_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE psl_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) psl_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	psl_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to psl_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       psl_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE psl_yy_scan_string (yyconst char * yystr )
{
    
	return psl_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to psl_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE psl_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) psl_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in psl_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = psl_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in psl_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up psl_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		psl_yytext[psl_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = psl_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		psl_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int psl_yyget_lineno  (void)
{
        
    return psl_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *psl_yyget_in  (void)
{
        return psl_yyin;
}

/** Get the output stream.
 * 
 */
FILE *psl_yyget_out  (void)
{
        return psl_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t psl_yyget_leng  (void)
{
        return psl_yyleng;
}

/** Get the current token.
 * 
 */

char *psl_yyget_text  (void)
{
        return psl_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void psl_yyset_lineno (int  line_number )
{
    
    psl_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see psl_yy_switch_to_buffer
 */
void psl_yyset_in (FILE *  in_str )
{
        psl_yyin = in_str ;
}

void psl_yyset_out (FILE *  out_str )
{
        psl_yyout = out_str ;
}

int psl_yyget_debug  (void)
{
        return psl_yy_flex_debug;
}

void psl_yyset_debug (int  bdebug )
{
        psl_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from psl_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch psl_yylineno unless the option is enabled. */
    psl_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    psl_yyin = stdin;
    psl_yyout = stdout;
#else
    psl_yyin = (FILE *) 0;
    psl_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * psl_yylex_init()
     */
    return 0;
}

/* psl_yylex_destroy is for both reentrant and non-reentrant scanners. */
int psl_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		psl_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		psl_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	psl_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * psl_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *psl_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *psl_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void psl_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see psl_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 518 "psl_input.l"



static int psl_skip_comment()
{
  register int c;

  do { c = input(); } while ( c != '\n' && c != EOF );
  return 0;
}

